<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_resultDiv.table.tbody.tr</name>
   <tag></tag>
   <elementGuidId>232728df-cdf7-4941-82a9-700a282a9270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='resultDiv']/table/tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='resultDiv']/table/tbody/tr</value>
   </webElementProperties>
</WebElementEntity>
